
[font]
size = 12.0

[font.bold]
family = "Meslo LG S DZ Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Meslo LG S DZ Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Meslo LG S DZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Meslo LG S DZ Nerd Font Mono"
style = "Regular"

[scrolling]
multiplier = 0

[general]
ipc_socket = false

[terminal]

[terminal.shell]
#args = ["--login"]
program = "/bin/bash"
