ipc_socket = false

[font]
size = 12.0

[font.bold]
family = "Meslo LG S DZ"
style = "Bold"

[font.bold_italic]
family = "Meslo LG S DZ"
style = "Bold Italic"

[font.italic]
family = "Meslo LG S DZ"
style = "Italic"

[font.normal]
family = "Meslo LG S DZ"
style = "Regular"

[scrolling]
multiplier = 0

[shell]
#args = ["--login"]
program = "/bin/bash"
