alias d='/bin/df -h'
alias la='/bin/ls -laFhN --color=auto'
alias cat='/usr/bin/cat -v'
alias cal='LC_ALL="de_DE.UTF-8" /usr/bin/cal'
alias gdb='/usr/bin/gdb -q'
alias n='/usr/bin/newsboat'
alias fuck='/usr/bin/sudo `history -p "!!"`'
alias excuse='/bin/telnet towel.blinkenlights.nl 666'
alias decide='/bin/ls -A | /bin/head -n $(($RANDOM % $(/bin/ls -A | /bin/wc -l))) | /bin/tail -1'
alias up='aur sync -u -c -d custom && sudo pacman -Syu && sudo pacdiff'
